installHook.js:1 TypeError: Cannot destructure property 'user' of 'useOutletContext(...)' as it is null.     at ProjectActivity (ProjectActivity.jsx:9:13)     at Object.react_stack_bottom_frame (react-dom_client.js?v=ad103596:18509:20)     at renderWithHooks (react-dom_client.js?v=ad103596:5654:24)     at updateFunctionComponent (react-dom_client.js?v=ad103596:7475:21)     at beginWork (react-dom_client.js?v=ad103596:8484:199)     at runWithFiberInDEV (react-dom_client.js?v=ad103596:997:72)     at performUnitOfWork (react-dom_client.js?v=ad103596:12561:98)     at workLoopSync (react-dom_client.js?v=ad103596:12424:43)     at renderRootSync (react-dom_client.js?v=ad103596:12408:13)     at performWorkOnRoot (react-dom_client.js?v=ad103596:11827:37)
The above error occurred in the <ProjectActivity> component.

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.

overrideMethod @ installHook.js:1
installHook.js:1 ErrorBoundary caught an error: TypeError: Cannot destructure property 'user' of 'useOutletContext(...)' as it is null.
    at ProjectActivity (ProjectActivity.jsx:9:13)
    at Object.react_stack_bottom_frame (react-dom_client.js?v=ad103596:18509:20)
    at renderWithHooks (react-dom_client.js?v=ad103596:5654:24)
    at updateFunctionComponent (react-dom_client.js?v=ad103596:7475:21)
    at beginWork (react-dom_client.js?v=ad103596:8484:199)
    at runWithFiberInDEV (react-dom_client.js?v=ad103596:997:72)
    at performUnitOfWork (react-dom_client.js?v=ad103596:12561:98)
    at workLoopSync (react-dom_client.js?v=ad103596:12424:43)
    at renderRootSync (react-dom_client.js?v=ad103596:12408:13)
    at performWorkOnRoot (react-dom_client.js?v=ad103596:11827:37) Object
overrideMethod @ installHook.js:1